{% set name = "horovod" %}
{% set version = "0.21.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/horovod/horovod.git
  git_rev: v{{ version }}

build:
  number: 8
  string: cuda{{ cudatoolkit | replace(".*", "") }}_{{ mpi_type }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}
  script_env:
    - CUDA_HOME
    - MPI_DIR

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
    - cmake             {{ cmake       }}
    - dataclasses       0.7               #[py == 36]
    - python            {{ python      }}
    - cffi              {{ cffi        }}
    - six               {{ six         }}
    - pyyaml            {{ pyyaml      }}
    - psutil            {{ psutil      }}
    - cloudpickle       {{ cloudpickle }}
    - openmpi           {{ openmpi     }} #[mpi_type == 'openmpi']
    - nccl              {{ nccl        }}
    - tensorflow        {{ tensorflow  }}
    - pytorch           {{ pytorch }}
  host:
    - python            {{ python      }}
    - cffi              {{ cffi        }}
    - six               {{ six         }}
    - make
    - pyyaml            {{ pyyaml      }}
    - psutil            {{ psutil      }}
    - cloudpickle       {{ cloudpickle }}
    - openmpi           {{ openmpi     }} #[mpi_type == 'openmpi']
    - nccl              {{ nccl        }}
    - tensorflow        {{ tensorflow  }}
    - pytorch           {{ pytorch }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
  run:
    - python            {{ python      }}
    - dataclasses       0.7               #[py == 36]
    - cudatoolkit       {{ cudatoolkit }}
    - cffi              {{ cffi        }}
    - six               {{ six         }}
    - pyyaml            {{ pyyaml      }}
    - psutil            {{ psutil      }}
    - cloudpickle       {{ cloudpickle }}
    - openmpi           {{ openmpi     }} #[mpi_type == 'openmpi']
    - nccl              {{ nccl        }}
    - pytest            {{ pytest      }}
  run_constrained:
    - tensorflow        {{ tensorflow }}
    - pytorch           {{ pytorch }}
about:
  home: https://github.com/horovod/horovod.git
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Distributed training framework for TensorFlow, Keras, PyTorch, and Apache MXNet.
  description: Distributed training framework for TensorFlow, Keras, PyTorch, and Apache MXNet.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
