#!/usr/bin/sh
# *****************************************************************
# (C) Copyright IBM Corp. 2020, 2021. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# *****************************************************************

BASEDIR=$CONDA_PREFIX
SUBDIRS="horovod"

if [ -z "$1" -o ! -z "$2" ]
then
    echo "Usage: $0 <directory>"
    echo "Copies samples ($SUBDIRS) to <directory>"
    echo "Will create <directory> if it does not exist."
    exit 1
fi

if [ -z $CONDA_PREFIX ]
then
    echo "CONDA_PREFIX is not set. A conda environment must be activated"
    echo "before running this command. Run: conda activate [<env>]"
    exit 1
fi

if [ ! -d "$1" ]
then
    echo "Creating directory $1"
    if ! mkdir -p "$1"
    then
        echo "Failed to create directory $1"
        exit 1
    fi
else
    echo "Write into existing directory $1? (yN)"
    read answer
    case "$answer" in
        y*|Y*)  :
                ;;
        *)      echo "Quit."
                exit 1
                ;;
    esac
fi

for d in $SUBDIRS
do
    if [ ! -d "$BASEDIR/$d" ]
    then
        echo "Unable to copy $BASEDIR/$d. The directory does not exist."
        echo "Make sure horovod conda package is installed."
        exit 1
    fi
    echo "Copying $d/ into $1..."
    if ! cp -r "$BASEDIR/$d" "$1"
    then
        echo "Copy failed"
        exit 1
    fi
done

echo "Success"

exit 0

